# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Auto Migration
on:
  push:
    branches:
      - master
  pull_request:
    branches: 
      - master

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - run: npm i
  migrate:
    runs-on: ubuntu-latest
    steps:
      - run: sequelize db:migrate
